(()=>{'use strict';
const SURL='https://kbtjkjdjvkorekzzhxcx.supabase.co';
const SKEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const client=window.supabase?.createClient(SURL,SKEY);let mode=null;
const $=s=>document.querySelector(s),show=(el,on)=>el?.classList.toggle('hidden',!on);
function forgotButton(){let b=$('#authForgot');if(b)return b;const row=$('#loginBtn')?.closest('.row');if(!row)return null;b=document.createElement('button');b.id='authForgot';b.type='button';b.className='btn outline hidden';b.textContent='Olvidé mi contraseña';row.parentNode.insertBefore(b,row.nextSibling);b.addEventListener('click',requestReset);return b}
function landing(){mode=null;show($('#authLanding'),true);show($('#authForm'),false);if($('#authMsg'))$('#authMsg').textContent='';if($('#loginBtn'))$('#loginBtn').disabled=false;show(forgotButton(),false)}
function open(m){mode=m;show($('#authLanding'),false);show($('#authForm'),true);const signup=m==='signup-family';show($('#nameField'),signup);show($('#confirmField'),signup);show($('#emailField'),true);show(forgotButton(),!signup&&['family','staff'].includes(m));$('#passwordLabel').textContent='CONTRASEÑA';$('#password').type='password';$('#password').inputMode='text';$('#password').maxLength=128;$('#password').minLength=6;$('#password').autocomplete=signup?'new-password':'current-password';$('#authTitle').textContent=signup?'Registro de familia':m==='staff'?'Maestra':'Familia';$('#authHint').textContent=signup?'Crea tu cuenta familiar y luego podrás vincular tus hijos desde Mountain.':m==='staff'?'Accede con tu cuenta autorizada por Mountain.':'Accede con tu correo y contraseña.';$('#loginBtn').textContent=signup?'Crear cuenta y entrar':'Iniciar sesión';$('#loginBtn').disabled=false;$('#authMsg').textContent='';$('#password').value='';if($('#password2'))$('#password2').value='';}
function recoveryForm(invite=false){mode='recovery';show($('#authLanding'),false);show($('#authForm'),true);show($('#nameField'),false);show($('#emailField'),false);show($('#confirmField'),true);show(forgotButton(),false);$('#authTitle').textContent=invite?'Crear contraseña':'Nueva contraseña';$('#authHint').textContent=invite?'Define una contraseña para completar tu acceso a Mountain Family.':'Escribe tu nueva contraseña.';$('#passwordLabel').textContent='NUEVA CONTRASEÑA';$('#password').autocomplete='new-password';$('#password').minLength=6;$('#password2').autocomplete='new-password';$('#loginBtn').textContent='Guardar contraseña';$('#loginBtn').disabled=false;$('#authMsg').textContent='';$('#password').value='';$('#password2').value='';}
async function requestReset(){if(!client)return;const email=$('#email').value.trim().toLowerCase();if(!email)return void($('#authMsg').textContent='Escribe primero tu correo.');const b=$('#authForgot');b.disabled=true;$('#authMsg').textContent='Preparando recuperación…';try{const redirectTo=location.origin+location.pathname;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;$('#authMsg').textContent='Si el correo está registrado, recibirás un enlace para crear una nueva contraseña.'}catch(e){$('#authMsg').textContent='No se pudo iniciar la recuperación. Inténtalo nuevamente.'}finally{b.disabled=false}}
async function submit(e){e?.preventDefault();e?.stopImmediatePropagation();if(!mode||mode==='admin')return;if(!client)return void($('#authMsg').textContent='No se pudo cargar el servicio de acceso.');const password=$('#password').value;if(mode==='recovery'){const p2=$('#password2').value;if(password.length<6)return void($('#authMsg').textContent='Usa una contraseña de al menos 6 caracteres.');if(password!==p2)return void($('#authMsg').textContent='Las contraseñas no coinciden.');$('#loginBtn').disabled=true;try{const {error}=await client.auth.updateUser({password});if(error)throw error;await client.auth.signOut();history.replaceState(null,'',location.pathname);landing();alert('Contraseña actualizada. Ya puedes iniciar sesión.')}catch(err){$('#authMsg').textContent='No se pudo actualizar la contraseña. Abre nuevamente el enlace recibido.';$('#loginBtn').disabled=false}return}
const email=$('#email').value.trim().toLowerCase();if(!email||password.length<6)return void($('#authMsg').textContent='Introduce correo y una contraseña de al menos 6 caracteres.');$('#loginBtn').disabled=true;try{if(mode==='signup-family'){const name=$('#fullName').value.trim(),p2=$('#password2').value;if(!name)throw new Error('Escribe tu nombre completo.');if(password!==p2)throw new Error('Las contraseñas no coinciden.');const r=await fetch(SURL+'/functions/v1/mountain-register-cors',{method:'POST',headers:{'Content-Type':'application/json','apikey':SKEY},body:JSON.stringify({full_name:name,email,password})});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'No se pudo crear la cuenta.');}
const {data,error}=await client.auth.signInWithPassword({email,password});if(error||!data?.user)throw new Error('Correo o contraseña incorrectos.');const {data:p,error:pe}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(pe||!p?.active){await client.auth.signOut();throw new Error('Cuenta no activa.');}const expected=mode==='staff'?'teacher':'family';if(p.role!==expected){await client.auth.signOut();throw new Error('Esta cuenta no tiene autorizado este tipo de acceso.');}location.reload();}catch(err){$('#authMsg').textContent=err.message||'No se pudo completar el acceso.';$('#loginBtn').disabled=false;}}
function linkType(){const h=new URLSearchParams(location.hash.replace(/^#/,'')),q=new URLSearchParams(location.search);return h.get('type')||q.get('type')||''}
document.addEventListener('DOMContentLoaded',()=>{forgotButton();document.querySelectorAll('[data-authmode]').forEach(b=>{if(b.dataset.authmode==='admin')return;b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open(b.dataset.authmode)},true)});$('#authBack')?.addEventListener('click',e=>{e.preventDefault();landing()},true);$('#loginBtn')?.addEventListener('click',submit,true);['email','password','password2'].forEach(id=>$('#'+id)?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();submit(e)}},true));const t=linkType();if(t==='invite'||t==='recovery')recoveryForm(t==='invite')});
client?.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>recoveryForm(false),0)});
window.MountainAccessV6={landing,open,recoveryForm};
})();