(()=>{'use strict';
const SURL='https://kbtjkjdjvkorekzzhxcx.supabase.co';
const SKEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const client=window.MountainRuntime?.sb||window.supabase?.createClient(SURL,SKEY);let mode=null;
const $=s=>document.querySelector(s),show=(el,on)=>el?.classList.toggle('hidden',!on);
function forgotButton(){let b=$('#authForgot');if(b)return b;const row=$('#loginBtn')?.closest('.row');if(!row)return null;b=document.createElement('button');b.id='authForgot';b.type='button';b.className='btn outline hidden';b.textContent='Olvidé mi contraseña';row.parentNode.insertBefore(b,row.nextSibling);b.addEventListener('click',requestReset);return b}
function landing(){mode=null;show($('#authLanding'),true);show($('#authForm'),false);if($('#authMsg'))$('#authMsg').textContent='';if($('#loginBtn'))$('#loginBtn').disabled=false;show(forgotButton(),false)}
function open(m){if(!['family','staff'].includes(m))return;mode=m;show($('#authLanding'),false);show($('#authForm'),true);show($('#nameField'),false);show($('#confirmField'),false);show($('#emailField'),true);show(forgotButton(),true);$('#passwordLabel').textContent='CONTRASEÑA';$('#password').type='password';$('#password').inputMode='text';$('#password').maxLength=128;$('#password').minLength=6;$('#password').autocomplete='current-password';$('#authTitle').textContent=m==='staff'?'Acceso de maestra':'Acceso de familia';$('#authHint').textContent=m==='staff'?'Ingresa con la cuenta creada por administración de Mountain.':'Ingresa con la cuenta creada por administración de Mountain.';$('#loginBtn').textContent='Iniciar sesión';$('#loginBtn').disabled=false;$('#authMsg').textContent='';$('#password').value='';if($('#password2'))$('#password2').value=''}
function recoveryForm(invite=false,forced=false){mode=forced?'forced-password':'recovery';show($('#authLanding'),false);show($('#authForm'),true);show($('#nameField'),false);show($('#emailField'),false);show($('#confirmField'),true);show(forgotButton(),false);show($('#authBack'),!forced);$('#authTitle').textContent=forced?'Crea tu contraseña personal':invite?'Crear contraseña':'Nueva contraseña';$('#authHint').textContent=forced?'Entraste con una contraseña temporal creada por administración. Por seguridad debes reemplazarla antes de continuar.':invite?'Define una contraseña de al menos 8 caracteres para completar tu acceso a Mountain Family.':'Escribe una nueva contraseña de al menos 8 caracteres.';$('#passwordLabel').textContent='NUEVA CONTRASEÑA';$('#password').autocomplete='new-password';$('#password').minLength=8;$('#password2').autocomplete='new-password';$('#password2').minLength=8;$('#loginBtn').textContent=forced?'Guardar y continuar':'Guardar contraseña';$('#loginBtn').disabled=false;$('#authMsg').textContent='';$('#password').value='';$('#password2').value=''}
async function requestReset(){if(!client)return;const email=$('#email').value.trim().toLowerCase();if(!email)return void($('#authMsg').textContent='Escribe primero tu correo.');const b=$('#authForgot');b.disabled=true;$('#authMsg').textContent='Preparando recuperación…';try{const redirectTo=location.origin+location.pathname;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;$('#authMsg').textContent='Si el correo está registrado, recibirás un enlace para crear una nueva contraseña.'}catch{$('#authMsg').textContent='No se pudo iniciar la recuperación. Inténtalo nuevamente.'}finally{b.disabled=false}}
async function saveNewPassword(forced){const password=$('#password').value,p2=$('#password2').value;if(password.length<8)return void($('#authMsg').textContent='Usa una contraseña de al menos 8 caracteres.');if(password!==p2)return void($('#authMsg').textContent='Las contraseñas no coinciden.');$('#loginBtn').disabled=true;try{const {data:{user}}=await client.auth.getUser();const metadata={...(user?.user_metadata||{}),must_change_password:false};const {error}=await client.auth.updateUser({password,data:metadata});if(error)throw error;if(forced){location.reload();return}await client.auth.signOut();history.replaceState(null,'',location.pathname);landing();alert('Contraseña actualizada. Ya puedes iniciar sesión.')}catch{$('#authMsg').textContent='No se pudo actualizar la contraseña. Inténtalo nuevamente.';$('#loginBtn').disabled=false}}
async function submit(e){e?.preventDefault();e?.stopImmediatePropagation();if(!mode||mode==='admin')return;if(!client)return void($('#authMsg').textContent='No se pudo cargar el servicio de acceso.');if(mode==='recovery'||mode==='forced-password')return saveNewPassword(mode==='forced-password');const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;if(!email||password.length<6)return void($('#authMsg').textContent='Introduce correo y contraseña.');$('#loginBtn').disabled=true;try{const {data,error}=await client.auth.signInWithPassword({email,password});if(error||!data?.user)throw new Error('Correo o contraseña incorrectos.');const {data:p,error:pe}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(pe||!p?.active){await client.auth.signOut();throw new Error('Cuenta sin acceso activo. Contacta a administración.')}const expected=mode==='staff'?'teacher':'family';if(p.role!==expected){await client.auth.signOut();throw new Error('Esta cuenta no tiene autorizado este tipo de acceso.')}if(data.user.user_metadata?.must_change_password){recoveryForm(false,true);return}location.reload()}catch(err){$('#authMsg').textContent=err.message||'No se pudo completar el acceso.';$('#loginBtn').disabled=false}}
function linkType(){const h=new URLSearchParams(location.hash.replace(/^#/,'')),q=new URLSearchParams(location.search);return h.get('type')||q.get('type')||''}
async function enforceExistingSession(){try{const {data:{session}}=await client.auth.getSession();if(!session?.user)return;if(session.user.user_metadata?.must_change_password)recoveryForm(false,true)}catch{}}
document.addEventListener('DOMContentLoaded',()=>{forgotButton();document.querySelectorAll('[data-authmode]').forEach(b=>{if(b.dataset.authmode==='admin')return;b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open(b.dataset.authmode)},true)});$('#authBack')?.addEventListener('click',e=>{e.preventDefault();landing()},true);$('#loginBtn')?.addEventListener('click',submit,true);['email','password','password2'].forEach(id=>$('#'+id)?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();submit(e)}},true));const t=linkType();if(t==='invite'||t==='recovery')recoveryForm(t==='invite');else enforceExistingSession()});
client?.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>recoveryForm(false),0);else if(session?.user?.user_metadata?.must_change_password)setTimeout(()=>recoveryForm(false,true),0)});
window.MountainAccessV6={landing,open,recoveryForm};
})();