(()=>{'use strict';
const SURL='https://kbtjkjdjvkorekzzhxcx.supabase.co';
const SKEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const client=window.supabase?.createClient(SURL,SKEY);let mode=null;
const $=s=>document.querySelector(s),show=(el,on)=>el?.classList.toggle('hidden',!on);
function open(m){mode=m;show($('#authLanding'),false);show($('#authForm'),true);const signup=m==='signup-family';show($('#nameField'),signup);show($('#confirmField'),signup);show($('#emailField'),true);$('#passwordLabel').textContent='CONTRASEÑA';$('#password').type='password';$('#password').inputMode='text';$('#password').maxLength=128;$('#password').minLength=6;$('#authTitle').textContent=signup?'Registro de familia':m==='staff'?'Maestra':'Familia';$('#authHint').textContent=signup?'Crea tu cuenta familiar y luego podrás vincular tus hijos desde Mountain.':m==='staff'?'Accede con tu cuenta autorizada por Mountain.':'Accede con tu correo y contraseña.';$('#loginBtn').textContent=signup?'Crear cuenta y entrar':'Iniciar sesión';$('#authMsg').textContent='';$('#password').value='';}
async function submit(e){e?.preventDefault();e?.stopImmediatePropagation();if(!mode||mode==='admin')return;if(!client)return void($('#authMsg').textContent='No se pudo cargar el servicio de acceso.');const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;if(!email||password.length<6)return void($('#authMsg').textContent='Introduce correo y una contraseña de al menos 6 caracteres.');$('#loginBtn').disabled=true;try{if(mode==='signup-family'){const name=$('#fullName').value.trim(),p2=$('#password2').value;if(!name)throw new Error('Escribe tu nombre completo.');if(password!==p2)throw new Error('Las contraseñas no coinciden.');const r=await fetch(SURL+'/functions/v1/mountain-register-cors',{method:'POST',headers:{'Content-Type':'application/json','apikey':SKEY},body:JSON.stringify({full_name:name,email,password})});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'No se pudo crear la cuenta.');}
const {data,error}=await client.auth.signInWithPassword({email,password});if(error||!data?.user)throw new Error('Correo o contraseña incorrectos.');const {data:p,error:pe}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(pe||!p?.active)throw new Error('Cuenta no activa.');const expected=mode==='staff'?'teacher':'family';if(p.role!==expected){await client.auth.signOut();throw new Error('Esta cuenta no tiene autorizado este tipo de acceso.');}location.reload();}catch(err){$('#authMsg').textContent=err.message||'No se pudo completar el acceso.';$('#loginBtn').disabled=false;}}
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('[data-authmode]').forEach(b=>{if(b.dataset.authmode==='admin')return;b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open(b.dataset.authmode)},true)});
 $('#loginBtn')?.addEventListener('click',submit,true);
 ['email','password','password2'].forEach(id=>$('#'+id)?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();submit(e)}},true));
});
})();