(()=>{'use strict';
const SURL='https://kbtjkjdjvkorekzzhxcx.supabase.co',SKEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const client=window.supabase?.createClient(SURL,SKEY);let mode='family';
const $=s=>document.querySelector(s), show=(el,on)=>el?.classList.toggle('hidden',!on);
function landing(){show($('#authLanding'),true);show($('#authForm'),false);$('#authMsg').textContent=''}
function form(m){mode=m;show($('#authLanding'),false);show($('#authForm'),true);const signup=m.startsWith('signup-');show($('#nameField'),signup);show($('#confirmField'),signup);$('#password').autocomplete=signup?'new-password':'current-password';const map={admin:['Administrador','Acceso exclusivo de administración.'],family:['Familia','Accede a la información de tus hijos vinculados por Mountain.'],staff:['Maestra','Acceso para personal docente autorizado.'],'signup-family':['Registro de familia','Crea tu cuenta. Mountain vinculará posteriormente tus hijos a este acceso.'],'signup-admin':['Registro de administrador','Solo un correo autorizado previamente por Mountain puede obtener rol Administrador.']};$('#authTitle').textContent=map[m][0];$('#authHint').textContent=map[m][1];$('#loginBtn').textContent=signup?'Crear cuenta':'Iniciar sesión';$('#authMsg').textContent=''}
async function submit(){if(!client)return void($('#authMsg').textContent='No se pudo cargar el servicio de acceso.');const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;$('#authMsg').textContent='';if(!email||password.length<8)return void($('#authMsg').textContent='Introduce un correo válido y una contraseña de al menos 8 caracteres.');const signup=mode.startsWith('signup-');if(signup){const name=$('#fullName').value.trim(),p2=$('#password2').value;if(!name)return void($('#authMsg').textContent='Escribe tu nombre completo.');if(password!==p2)return void($('#authMsg').textContent='Las contraseñas no coinciden.');$('#loginBtn').disabled=true;const requested_role=mode==='signup-admin'?'admin':'family';const {data,error}=await client.auth.signUp({email,password,options:{data:{full_name:name,requested_role,preferred_language:'es'}}});$('#loginBtn').disabled=false;if(error)return void($('#authMsg').textContent=error.message);if(data.session){location.reload()}else{$('#authMsg').textContent='Cuenta creada. Revisa tu correo para confirmar el acceso y luego inicia sesión.'}return}
$('#loginBtn').disabled=true;const {data,error}=await client.auth.signInWithPassword({email,password});$('#loginBtn').disabled=false;if(error)return void($('#authMsg').textContent='No fue posible iniciar sesión. Verifica el correo y la contraseña.');const {data:p}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();const expected=mode==='admin'?'admin':mode==='staff'?'teacher':'family';if(!p?.active||p.role!==expected){await client.auth.signOut();return void($('#authMsg').textContent=`Esta cuenta no tiene acceso como ${mode==='staff'?'maestra':mode}.`)}location.reload()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-authmode]').forEach(b=>b.addEventListener('click',()=>form(b.dataset.authmode)));$('#authBack')?.addEventListener('click',landing);$('#loginBtn')?.addEventListener('click',submit);['email','password','password2'].forEach(id=>$('#'+id)?.addEventListener('keydown',e=>{if(e.key==='Enter')submit()}));});
window.MountainAuthV4={landing,form};
})();