(()=>{'use strict';
const SURL='https://kbtjkjdjvkorekzzhxcx.supabase.co',SKEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const client=window.supabase?.createClient(SURL,SKEY);let mode='family';
const $=s=>document.querySelector(s),show=(el,on)=>el?.classList.toggle('hidden',!on);
function landing(){show($('#authLanding'),true);show($('#authForm'),false);$('#authMsg').textContent=''}
function form(m){mode=m;show($('#authLanding'),false);show($('#authForm'),true);const signup=m==='signup-family',admin=m==='admin';show($('#nameField'),signup);show($('#confirmField'),signup);show($('#emailField'),!admin);$('#passwordLabel').textContent=admin?'PIN DE 4 DÍGITOS':'CONTRASEÑA';$('#password').type='password';$('#password').inputMode=admin?'numeric':'text';$('#password').maxLength=admin?4:128;$('#password').minLength=admin?4:8;$('#password').autocomplete=signup?'new-password':'current-password';const map={admin:['Administrador','Acceso privado de administración. Introduce tu PIN de 4 dígitos.'],family:['Familia','Accede a la información de tus hijos vinculados por Mountain.'],staff:['Maestra','Acceso para personal docente autorizado.'],'signup-family':['Registro de familia','Crea tu cuenta familiar y entra inmediatamente.']};$('#authTitle').textContent=map[m][0];$('#authHint').textContent=map[m][1];$('#loginBtn').textContent=signup?'Crear cuenta y entrar':admin?'Entrar con PIN':'Iniciar sesión';$('#authMsg').textContent='';$('#password').value=''}
async function adminPin(){const pin=$('#password').value.trim();if(!/^\d{4}$/.test(pin))return void($('#authMsg').textContent='Introduce tu PIN de 4 dígitos.');$('#loginBtn').disabled=true;$('#authMsg').textContent='Verificando acceso…';let response;try{response=await fetch(`${SURL}/functions/v1/mountain-admin-pin`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SKEY},body:JSON.stringify({pin})})}catch(e){$('#loginBtn').disabled=false;return void($('#authMsg').textContent='No fue posible conectar con el acceso administrativo.')}const result=await response.json().catch(()=>({error:'Respuesta inválida'}));if(!response.ok||result.error){$('#loginBtn').disabled=false;return void($('#authMsg').textContent=result.error||'No fue posible iniciar sesión.')}const {data,error}=await client.auth.verifyOtp({token_hash:result.token_hash,type:'magiclink'});$('#loginBtn').disabled=false;if(error||!data?.user)return void($('#authMsg').textContent='No fue posible establecer la sesión administrativa.');const {data:p}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();if(!p?.active||p.role!=='admin'){await client.auth.signOut();return void($('#authMsg').textContent='Cuenta sin autorización administrativa.')}location.reload()}
async function submit(){if(!client)return void($('#authMsg').textContent='No se pudo cargar el servicio de acceso.');if(mode==='admin')return adminPin();const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;$('#authMsg').textContent='';if(!email||password.length<8)return void($('#authMsg').textContent='Introduce un correo válido y una contraseña de al menos 8 caracteres.');if(mode==='signup-family'){const name=$('#fullName').value.trim(),p2=$('#password2').value;if(!name)return void($('#authMsg').textContent='Escribe tu nombre completo.');if(password!==p2)return void($('#authMsg').textContent='Las contraseñas no coinciden.');$('#loginBtn').disabled=true;const response=await fetch(`${SURL}/functions/v1/mountain-register`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SKEY},body:JSON.stringify({email,password,full_name:name,requested_role:'family'})}).catch(()=>null);const result=response?await response.json().catch(()=>({error:'Respuesta inválida'})):{error:'No fue posible conectar con el registro.'};if(!response?.ok||result.error){$('#loginBtn').disabled=false;return void($('#authMsg').textContent=result.error||'No se pudo crear la cuenta.')}const {data,error}=await client.auth.signInWithPassword({email,password});$('#loginBtn').disabled=false;if(error||!data?.user)return void($('#authMsg').textContent='Cuenta creada. Inicia sesión con la misma contraseña.');location.reload();return}$('#loginBtn').disabled=true;const {data,error}=await client.auth.signInWithPassword({email,password});$('#loginBtn').disabled=false;if(error)return void($('#authMsg').textContent='No fue posible iniciar sesión. Verifica tus datos.');const {data:p}=await client.from('mf_profiles').select('role,active').eq('id',data.user.id).maybeSingle();const expected=mode==='staff'?'teacher':'family';if(!p?.active||p.role!==expected){await client.auth.signOut();return void($('#authMsg').textContent='Esta cuenta no tiene autorizado este tipo de acceso.')}location.reload()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-authmode]').forEach(b=>b.addEventListener('click',()=>form(b.dataset.authmode)));$('#authBack')?.addEventListener('click',landing);const b=$('#loginBtn');if(b){b.onclick=null;b.addEventListener('click',submit)}['email','password','password2'].forEach(id=>$('#'+id)?.addEventListener('keydown',e=>{if(e.key==='Enter')submit()}));});
window.MountainAuthV5={landing,form};
})();