(()=>{'use strict';
const URL='https://kbtjkjdjvkorekzzhxcx.supabase.co',KEY='sb_publishable_4uce_DqQ7LpVOSnGAGnfmA_ZXEUWofq';
const sb=window.supabase?.createClient(URL,KEY),$=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,lastSeen=new Set(),timer=null;
const fmt=d=>{try{return new Intl.DateTimeFormat('es-DO',{timeZone:'America/Santo_Domingo',dateStyle:'short',timeStyle:'short'}).format(new Date(d))}catch{return''}};
function modal(html){const m=$('#modal'),s=$('#sheet');if(!m||!s)return;s.innerHTML=html;m.classList.add('show')}
async function ensurePrefs(){if(!user)return null;let {data}=await sb.from('mf_notification_preferences').select('*').eq('user_id',user.id).maybeSingle();if(!data){const ins=await sb.from('mf_notification_preferences').insert({user_id:user.id}).select('*').single();data=ins.data}return data}
async function getNotices(){if(!user)return[];const {data}=await sb.from('mf_notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);return data||[]}
function badge(n){let b=$('#mfNotifyBadge');if(!b)return;b.textContent=n>99?'99+':String(n);b.classList.toggle('hidden',!n);const btn=$('#mfNotifyBtn');if(btn)btn.setAttribute('aria-label',n?`Notificaciones, ${n} sin leer`:'Notificaciones')}
async function refresh(showDevice=false){const rows=await getNotices();badge(rows.filter(x=>!x.read_at).length);if(showDevice&&'Notification'in window&&Notification.permission==='granted'){for(const n of rows.filter(x=>!x.read_at)){if(lastSeen.has(n.id))continue;lastSeen.add(n.id);if(Date.now()-new Date(n.created_at).getTime()<120000){try{new Notification(n.title,{body:n.body,icon:'assets/mountain-logo-192.png'})}catch(e){}}}}rows.forEach(x=>lastSeen.add(x.id));return rows}
async function openCenter(){const rows=await refresh(false);modal(`<div class="head"><div><h3>🔔 Notificaciones</h3><p>${rows.filter(x=>!x.read_at).length} sin leer</p></div><button class="btn soft" data-close>Cerrar</button></div><div class="row"><button id="mfReadAll" class="btn outline">Marcar todo leído</button><button id="mfNotifSettings" class="btn soft">Preferencias</button></div><div class="list mt">${rows.map(n=>`<div class="card ${n.read_at?'':'notice'}" data-notice="${n.id}"><div class="row"><b>${esc(n.title)}</b>${n.read_at?'':'<span class="badge urgent">NUEVO</span>'}</div><p>${esc(n.body)}</p><small class="meta">${esc(n.category)} · ${fmt(n.created_at)}</small></div>`).join('')||'<div class="notice">No tienes notificaciones.</div>'}</div>`);document.querySelectorAll('[data-notice]').forEach(el=>el.addEventListener('click',async()=>{await sb.from('mf_notifications').update({read_at:new Date().toISOString()}).eq('id',el.dataset.notice);el.classList.remove('notice');el.querySelector('.badge')?.remove();await refresh(false)}));$('#mfReadAll').onclick=async()=>{await sb.from('mf_notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);await openCenter()};$('#mfNotifSettings').onclick=settings}
async function settings(){const p=await ensurePrefs();if(!p)return;const fields=[['messages','Mensajes'],['checkin_checkout','Entrada y salida'],['meals','Comidas'],['naps','Siesta'],['diapers','Higiene / pañal'],['photos_videos','Fotos y videos'],['learning','Aprendizaje'],['incidents_health','Incidentes y salud'],['billing','Pagos'],['announcements','Comunicaciones institucionales']];modal(`<div class="head"><div><h3>Preferencias de notificación</h3><p>Elige qué avisos deseas recibir.</p></div><button class="btn soft" data-close>Cerrar</button></div><div class="list">${fields.map(([k,l])=>`<label class="checkrow"><input class="nfPref" type="checkbox" data-key="${k}" ${p[k]!==false?'checked':''}><span>${l}</span></label>`).join('')}</div><button id="nfSave" class="btn primary mt">Guardar preferencias</button>${'Notification'in window?`<button id="nfDevice" class="btn outline mt">${Notification.permission==='granted'?'Avisos del dispositivo activados':'Activar avisos del dispositivo'}</button>`:''}`);$('#nfSave').onclick=async()=>{const patch={user_id:user.id,updated_at:new Date().toISOString()};document.querySelectorAll('.nfPref').forEach(x=>patch[x.dataset.key]=x.checked);const {error}=await sb.from('mf_notification_preferences').upsert(patch,{onConflict:'user_id'});if(error)return alert(error.message);alert('Preferencias guardadas.');await openCenter()};if($('#nfDevice'))$('#nfDevice').onclick=async()=>{if(Notification.permission!=='granted')await Notification.requestPermission();await settings()}}
function addButton(){const top=document.querySelector('.topin');if(!top||$('#mfNotifyBtn'))return;const btn=document.createElement('button');btn.id='mfNotifyBtn';btn.className='btn soft';btn.style.position='relative';btn.innerHTML='🔔<span id="mfNotifyBadge" class="badge urgent hidden" style="position:absolute;right:-6px;top:-7px"></span>';btn.onclick=openCenter;const logout=$('#logoutBtn');top.insertBefore(btn,logout||null)}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session)return;user=session.user;addButton();await ensurePrefs();await refresh(false);timer=setInterval(()=>{if(document.visibilityState==='visible')refresh(true)},30000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh(true)})}
document.addEventListener('DOMContentLoaded',boot);window.MountainNotifications={open:openCenter,refresh:()=>refresh(false)};
})();