'use strict';
const API='https://iwpbzbjfsljqeajikytu.supabase.co/functions/v1/mcs-transport';
const $=id=>document.getElementById(id);let token='',map,bus,stopMarker,timer,lastData=null;
function fromHash(){const m=location.hash.match(/(?:^#|&)family=([a-f0-9]{64})/i);if(m){localStorage.setItem('mcs_family_token',m[1].toLowerCase());history.replaceState(null,'',location.pathname);}}
function getToken(){return localStorage.getItem('mcs_family_token')||'';}
async function call(action,extra={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-mcs-token':token},body:JSON.stringify({action,...extra}),cache:'no-store'});if(r.status===401)throw Error('unauthorized');if(!r.ok)throw Error('network');return await r.json();}
function fmtEta(s){if(s==null)return '—';if(s<=30)return 'Ahora';return Math.max(1,Math.ceil(s/60))+' min';}function fmtDist(m){if(m==null)return '—';return m<1000?Math.round(m)+' m':(m/1000).toFixed(1)+' km';}
function ensureMap(){if(map)return;map=L.map('map',{zoomControl:true}).setView([18.4612,-69.3021],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);}
function draw(d){ensureMap();if(stopMarker)stopMarker.remove();if(bus)bus.remove();if(d.stop){stopMarker=L.circleMarker([d.stop.lat,d.stop.lng],{radius:9,weight:3,color:'#c48625',fillOpacity:.85}).bindTooltip('Tu parada').addTo(map);}if(d.position){bus=L.marker([d.position.latitude,d.position.longitude]).bindTooltip('Autobús').addTo(map);}const pts=[];if(d.stop)pts.push([d.stop.lat,d.stop.lng]);if(d.position)pts.push([d.position.latitude,d.position.longitude]);if(pts.length)map.fitBounds(pts,{padding:[35,35],maxZoom:16});setTimeout(()=>map.invalidateSize(),50);}
function events(list){$('events').replaceChildren();for(const e of list||[]){const div=document.createElement('div');div.className='event';const small=document.createElement('small');small.textContent=new Date(e.created_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'});const p=document.createElement('p');const b=document.createElement('b');b.textContent=e.title;const text=document.createTextNode(' — '+e.body);p.append(b,text);div.append(small,p);$('events').append(div);}if(!(list||[]).length)$('events').textContent='Todavía no hay avisos para esta ruta.';}
function render(d){lastData=d;if(d.access!=='open'){$('windowBadge').textContent='FUERA DE HORARIO';$('headline').textContent=d.access==='closed'?'Seguimiento cerrado':'Acceso no asignado';$('status').textContent='La ubicación del autobús no está disponible en este momento.';$('eta').textContent='—';$('distance').textContent='—';if(map){map.remove();map=null;bus=null;stopMarker=null;}return;}$('windowBadge').textContent='ACCESO ACTIVO';const status=d.trip?.status||'waiting';$('headline').textContent=status==='active'?'Autobús en ruta':status==='arrived_school'?'Autobús en el colegio':'Ruta pendiente de iniciar';$('status').textContent=d.position?'Posición reciente recibida de la unidad.':'Esperando una señal GPS reciente.';$('eta').textContent=fmtEta(d.eta_seconds);$('distance').textContent=fmtDist(d.distance_m);draw(d);events(d.events);if(d.vapid_public)$('push').disabled=false;}
async function refresh(){try{render(await call('family_snapshot'));}catch(e){if(e.message==='unauthorized'){localStorage.removeItem('mcs_family_token');location.reload();}else $('status').textContent='No pudimos actualizar. Reintentaremos automáticamente.';}}
function schedule(){clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)refresh();},8000);}
function b64(s){const pad='='.repeat((4-s.length%4)%4);const raw=atob((s+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
async function enablePush(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('unsupported');if(!lastData?.vapid_public){await refresh();if(!lastData?.vapid_public)throw Error('not_ready');}const reg=await navigator.serviceWorker.register('./sw.js');const perm=await Notification.requestPermission();if(perm!=='granted')throw Error('denied');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(lastData.vapid_public)});await call('subscribe_push',{subscription:sub.toJSON()});$('pushState').textContent='Avisos activados en este dispositivo.';$('push').textContent='Avisos activos';$('push').disabled=true;}catch(e){$('pushState').textContent=e.message==='denied'?'Permiso de notificaciones rechazado. Puedes cambiarlo en los ajustes del dispositivo.':'Para recibir avisos en iPhone, añade la web a la pantalla de inicio y vuelve a intentarlo.';}}
fromHash();token=getToken();if(!token){$('login').classList.remove('hidden');$('saveToken').onclick=()=>{const v=$('tokenInput').value.trim().toLowerCase();if(/^[a-f0-9]{64}$/.test(v)){localStorage.setItem('mcs_family_token',v);location.reload();}};}else{$('app').classList.remove('hidden');$('push').disabled=true;$('push').onclick=enablePush;$('refresh').onclick=refresh;$('logout').onclick=()=>{localStorage.removeItem('mcs_family_token');location.reload();};refresh();schedule();document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});}