import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const read=p=>fs.readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const app=read('app-v3.js');
const html=read('index.html');
const css=read('styles-v2.css');
const sw=read('sw.js');
const manifest=JSON.parse(read('manifest.webmanifest'));
const has=(src,needle)=>src.includes(needle);
const cases=[];
const add=(name,fn)=>cases.push([name,fn]);

add('01 app-v3.js parses as JavaScript',()=>assert.doesNotThrow(()=>new vm.Script(app)));
add('02 index loads app-v3.js',()=>assert.ok(has(html,'app-v3.js')));
add('03 index loads styles-v2.css',()=>assert.ok(has(html,'styles-v2.css')));
add('04 index links manifest',()=>assert.ok(has(html,'manifest.webmanifest')));
add('05 index declares mobile viewport',()=>assert.ok(has(html,'viewport-fit=cover')));
add('06 index enables Apple web app mode',()=>assert.ok(has(html,'apple-mobile-web-app-capable')));
add('07 service worker caches app-v3.js',()=>assert.ok(has(sw,'./app-v3.js')));
add('08 service worker caches index.html',()=>assert.ok(has(sw,'./index.html')));
add('09 service worker caches stylesheet',()=>assert.ok(has(sw,'./styles-v2.css')));
add('10 service worker excludes Supabase requests from cache',()=>assert.ok(has(sw,"hostname.includes('supabase.co')")));
add('11 service worker excludes storage/function requests',()=>assert.ok(has(sw,"pathname.includes('/storage/')")&&has(sw,"pathname.includes('/functions/')")));
add('12 manifest names Mountain Family',()=>assert.equal(manifest.name,'Mountain Family'));
add('13 manifest is standalone PWA',()=>assert.equal(manifest.display,'standalone'));
add('14 manifest has start_url',()=>assert.ok(manifest.start_url));
add('15 manifest has icons',()=>assert.ok(Array.isArray(manifest.icons)&&manifest.icons.length>0));
add('16 Supabase project URL is configured',()=>assert.ok(has(app,'kbtjkjdjvkorekzzhxcx.supabase.co')));
add('17 publishable Supabase key is configured',()=>assert.ok(has(app,'sb_publishable_')));
add('18 app creates Supabase client',()=>assert.ok(has(app,'supabase.createClient')));
add('19 app restores authenticated session',()=>assert.ok(has(app,'auth.getSession()')));
add('20 app supports sign-in',()=>assert.ok(has(app,'signInWithPassword')));
add('21 app supports sign-out',()=>assert.ok(has(app,'auth.signOut()')));
add('22 app reads active user profile',()=>assert.ok(has(app,"from('mf_profiles')")));
add('23 app enforces active profile',()=>assert.ok(has(app,'p?.active')));
add('24 app implements role-aware family fallback',()=>assert.ok(has(app,"state.profile?.role||'family'")));
add('25 app recognizes admin and teacher as staff',()=>assert.ok(has(app,"['admin','teacher'].includes(role())")));
add('26 all six official grades are present',()=>['Maternal','Infantes','Párvulos','Pre-Kínder','Kínder','Preprimario'].forEach(g=>assert.ok(has(app,g))));
add('27 app reads classrooms',()=>assert.ok(has(app,"from('mf_classrooms')")));
add('28 app reads students',()=>assert.ok(has(app,"from('mf_students')")));
add('29 app loads selected student data',()=>assert.ok(has(app,'loadSelected()')));
add('30 app reads daily events',()=>assert.ok(has(app,"from('mf_daily_events')")));
add('31 family feed filters visible events',()=>assert.ok(has(app,"eq('visible_to_family',true)")));
add('32 app reads private attachments',()=>assert.ok(has(app,"from('mf_attachments')")));
add('33 attachments require accepted security status',()=>assert.ok(has(app,"eq('security_status','accepted')")));
add('34 deleted attachments are excluded',()=>assert.ok(has(app,"is('deleted_at',null)")));
add('35 app reads published broadcasts',()=>assert.ok(has(app,"from('mf_broadcasts')")&&has(app,"eq('status','published')")));
add('36 family delivery acknowledgement is wired',()=>assert.ok(has(app,'mf_mark_broadcast_delivered')));
add('37 family read acknowledgement is wired',()=>assert.ok(has(app,'mf_mark_broadcast_read')));
add('38 agent rules are loaded',()=>assert.ok(has(app,"from('mf_agent_rules')")));
add('39 Mounty drafts are loaded',()=>assert.ok(has(app,"from('mf_agent_drafts')")));
add('40 five primary views are wired',()=>['home','routine','academic','messages','more'].forEach(v=>assert.ok(has(app,`'${v}'`))));
add('41 admin home exposes attendance workflow',()=>assert.ok(has(app,'Entrada / salida')&&has(app,'data-action="attendance"')));
add('42 admin home exposes broadcast workflow',()=>assert.ok(has(app,'data-action="broadcast"')));
add('43 admin home exposes Mounty compose/review',()=>assert.ok(has(app,'data-action="mountyCompose"')&&has(app,'data-action="mounty"')));
add('44 admin home exposes incident workflow',()=>assert.ok(has(app,'data-action="incident"')));
add('45 admin home exposes media workflow',()=>assert.ok(has(app,'data-action="media"')));
add('46 admin home exposes authorized pickup workflow',()=>assert.ok(has(app,'data-action="pickups"')));
add('47 admin home exposes documents and payments',()=>assert.ok(has(app,'data-action="documents"')&&has(app,'data-action="payments"')));
add('48 CRECE five pillars are present',()=>['Creatividad','Ritmo','Exploración','Conexión','Equilibrio'].forEach(p=>assert.ok(has(app,p))));
add('49 daily institutional routine is fully represented',()=>assert.ok(has(app,'6:30–8:00')&&has(app,'12:30–2:30')&&has(app,'5:00–6:00')));
add('50 action router connects all major workflows',()=>['quick','attendance','pickups','documents','payments','safety','plans','observation','academicHistory','attendanceHistory','mounty','mountyCompose','broadcast','search','incident','thread','media'].forEach(a=>assert.ok(has(app,`${a}:`))));

assert.equal(cases.length,50,'The suite must contain exactly 50 tests');
for(const [name,fn] of cases)test(name,fn);
