import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const base=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,base),'utf8');
const exists=p=>fs.existsSync(new URL(p,base));
const files={
 runtime:read('runtime-v2.js'),network:read('network-guard-v1.js'),app:read('app-v3.js'),gate:read('admin-gate.js'),access:read('access-v6.js'),users:read('admin-users-v1.js'),adminData:read('admin-data-v1.js'),docs:read('admin-documents-v1.js'),familyDocs:read('family-documents-v1.js'),school:read('school-admin-v1.js'),academic:read('academic-v2.js'),guide:read('mounty-guide-v1.js'),teacher:read('teacher-experience-v1.js'),notifications:read('notifications-v1.js'),accountControls:read('account-controls-v1.js'),finalFlow:read('final-flow-v1.js'),a11y:read('styles-a11y-v1.css'),privacy:read('privacy.html'),deletion:read('account-deletion.html'),sw:read('sw.js'),html:read('index.html')
};
const manifest=JSON.parse(read('manifest.webmanifest'));
const guard=JSON.parse(read('RELEASE_GUARD.json'));
const has=(s,n)=>s.includes(n),contracts=[],add=(n,f)=>contracts.push([n,f]),contains=(f,t)=>()=>assert.ok(has(files[f],t),`${f} must contain ${t}`),notContains=(f,t)=>()=>assert.equal(has(files[f],t),false,`${f} must not contain ${t}`);
for(const [name,source] of Object.entries(files))if(!['html','sw','a11y','privacy','deletion'].includes(name))add(`${name} parses`,()=>assert.doesNotThrow(()=>new vm.Script(source)));

add('protected release marker',()=>assert.equal(guard.release,'MF-R5.5-MANAGED-ACCESS-20260912'));
add('protected baseline status',()=>assert.equal(guard.status,'protected-baseline'));
add('delivery model remains PWA',()=>assert.equal(guard.architecture.delivery_model,'PWA'));
add('native store binary not falsely claimed',()=>assert.equal(guard.architecture.native_store_binary_present,false));
add('transport stays separate',()=>assert.equal(guard.architecture.transport_app_is_separate,true));
add('exact six-grade baseline',()=>assert.deepEqual(guard.architecture.grades,['Maternal','Infantes','Párvulos','Pre-Kínder','Kínder','Preprimario']));
add('all five communication audiences protected',()=>assert.deepEqual(guard.architecture.communication_audiences,['all_families','cycle','classroom','single_student','selected_students']));
add('administrator-only family teacher provisioning',()=>assert.equal(guard.architecture.auth.family_teacher_provisioning,'administrator-only'));
add('public family registration disabled',()=>assert.equal(guard.architecture.auth.public_family_self_registration,false));
add('temporary password change required',()=>assert.equal(guard.architecture.auth.temporary_password_required_change,true));
add('administrator can reset temporary password',()=>assert.equal(guard.architecture.auth.admin_can_reset_temporary_password,true));
add('users can change own password',()=>assert.equal(guard.architecture.auth.user_can_change_own_password,true));
add('administrator revoke preserves history',()=>assert.equal(guard.architecture.auth.admin_can_revoke_access_without_deleting_history,true));
add('privacy policy invariant',()=>assert.equal(guard.architecture.privacy.public_policy,'privacy.html'));
add('external deletion invariant',()=>assert.equal(guard.architecture.privacy.external_deletion_resource,'account-deletion.html'));
add('in-app deletion invariant',()=>assert.equal(guard.architecture.privacy.in_app_family_deletion_request,'mountain-account-deletion-request'));
add('focus visibility invariant',()=>assert.equal(guard.architecture.accessibility.focus_visible,true));
add('offline status invariant',()=>assert.equal(guard.architecture.accessibility.offline_status,true));
add('Mounty human approval invariant',()=>assert.equal(guard.architecture.mounty.human_approval_required,true));
add('Mounty strict grounding invariant',()=>assert.equal(guard.architecture.mounty.strict_context_grounding,true));
add('Mounty structured error invariant',()=>assert.equal(guard.architecture.mounty.structured_error_reference,true));
add('Mounty retry invariant',()=>assert.equal(guard.architecture.mounty.retry_transient_ai_failures,true));
add('Mounty unified audience flow invariant',()=>assert.equal(guard.architecture.mounty.single_unified_audience_flow,true));

add('R5.5 marker',contains('html','MF-R5.5-MANAGED-ACCESS-20260912'));
add('Supabase dependency pinned',contains('html','@supabase/supabase-js@2.116.0'));
add('runtime loads before app',()=>assert.ok(files.html.indexOf('runtime-v2.js')<files.html.indexOf('app-v3.js')));
add('legacy auth absent from shell',notContains('html','auth-v5.js'));
add('public signup absent from shell',notContains('html','signup-family'));
add('public signup copy absent from shell',notContains('html','Registrarme como familia'));
add('managed access copy present',contains('html','creadas y administradas exclusivamente'));
add('retired admin endpoint absent from shell',notContains('html','mountain-admin-simple'));
add('temporary Mounty QA endpoint absent from shell',notContains('html','mounty-qa-temp'));
add('temporary role QA endpoint absent from shell',notContains('html','final-role-qa-temp'));
add('obsolete auth-v4 physically removed',()=>assert.equal(exists('auth-v4.js'),false));
add('obsolete auth-v5 physically removed',()=>assert.equal(exists('auth-v5.js'),false));
add('obsolete app-v2 physically removed',()=>assert.equal(exists('app-v2.js'),false));
add('obsolete family prototype physically removed',()=>assert.equal(exists('family/index.html'),false));
add('privacy link before sign in',contains('html','privacy.html'));
add('account deletion link before sign in',contains('html','account-deletion.html'));
add('account controls R5.5 loaded',contains('html','account-controls-v1.js?v=20260912-r5-5'));
add('managed access R5.5 loaded',contains('html','access-v6.js?v=20260912-r5-5'));
add('admin users R5.5 loaded',contains('html','admin-users-v1.js?v=20260912-r5-5'));
add('accessibility layer loaded',contains('html','styles-a11y-v1.css?v=20260912-r5-3'));
add('offline status element',contains('html','id="offlineBanner"'));
add('dialog semantic',contains('html','aria-modal="true"'));
add('skip link',contains('html','Saltar al contenido'));
add('runtime shared client',contains('runtime','window.supabase.createClient=(url,key,options)=>url===URL&&key===KEY?sb'));
add('runtime profile cache',contains('runtime','currentProfile'));
add('runtime auth events',contains('runtime','mountain:auth'));
add('runtime R5.1 reliability retained',contains('runtime','R5.1-MOUNTY-RELIABILITY'));
add('runtime parses Edge Function bodies',contains('runtime','parseFunctionError'));
add('runtime centralized invoke',contains('runtime','invokeFunction'));
add('runtime refreshes 401 session',contains('runtime','refreshSession'));
add('runtime supports retryable function errors',contains('runtime','last?.retryable'));
add('runtime hides raw non-2xx message',contains('runtime','edge function returned a non-2xx status code'));
add('runtime infers MIME',contains('runtime','inferMime'));

for(const g of ['Maternal','Infantes','Párvulos','Pre-Kínder','Kínder','Preprimario'])add(`grade ${g}`,contains('app',g));
for(const m of ['Desayuno','Almuerzo','Siesta','Higiene','Actividad pedagógica'])add(`routine ${m}`,contains('app',m));
add('admin PIN endpoint',contains('gate','mountain-admin-pin'));add('admin OTP',contains('gate','verifyOtp'));add('family teacher password login',contains('access','signInWithPassword'));add('family login role enforced',contains('access',"expected=mode==='staff'?'teacher':'family'"));add('temporary password metadata enforced',contains('access','must_change_password'));add('forced password screen',contains('access','Crea tu contraseña personal'));add('forced password metadata cleared',contains('access','must_change_password:false'));add('no registration endpoint in access UI',notContains('access','mountain-register-cors'));

add('admin users panel',contains('users','Usuarios y accesos'));add('admin creates managed account',contains('users',"action:'create'"));add('temporary password generator',contains('users','tempPassword'));add('admin temporary password reset',contains('users',"action:'reset_password'"));add('admin revokes access',contains('users',"action:'revoke_access'"));add('history retained copy',contains('users','No se borrarán sus registros históricos'));add('family assignment during account creation',contains('users','student_ids'));add('teacher assignment during account creation',contains('users','classroom_ids'));add('atomic classroom assignment',contains('users',"action:'set_classrooms'"));add('protected admin',contains('users','Cuenta administrativa principal protegida'));
add('user self-service password change',contains('accountControls','Cambiar contraseña'));add('own password update',contains('accountControls','auth.updateUser'));add('own password minimum eight',contains('accountControls','p.length<8'));
add('payment validation',contains('adminData','amount<=0'));add('pickup validation',contains('adminData','exactamente 4 dígitos'));add('future DOB blocked',contains('school','no puede estar en el futuro'));add('teacher planning scope',contains('school',"from('mf_classroom_staff')"));
add('academic core domains',()=>{for(const x of ['Lenguaje','Cognición','Socioemocional','Psicomotricidad fina','Psicomotricidad gruesa','Matemáticas','Lectoescritura','Inglés','Creatividad','Autonomía'])assert.ok(has(files.academic,x))});

add('document physical file required',contains('docs','Selecciona el archivo que deseas guardar.'));add('document signed upload',contains('docs','prepare_document_upload'));add('document rollback',contains('docs','cancel_document_upload'));add('family signed document read',contains('familyDocs','signed_document_read'));
add('Mounty centralized function invoke',contains('guide','rt.invokeFunction'));add('Mounty compose retries',contains('guide',"invoke('mounty-compose',body,{retry:true})"));add('Mounty no raw functions.invoke compose',notContains('guide',"sb.functions.invoke('mounty-compose'"));add('Mounty displays request reference',contains('guide','Referencia:'));add('Mounty generating state',contains('guide','Mounty está redactando…'));add('Mounty max context',contains('guide','maxlength="5000"'));add('Mounty selected audience validation',contains('guide','Selecciona al menos un estudiante.'));add('Mounty single student validation',contains('guide','Selecciona un estudiante.'));add('Mounty previews recipients',contains('guide','mf_broadcast_preview_count'));add('Mounty zero recipient guard',contains('guide','No hay familias activas vinculadas'));add('Mounty teacher classroom scope',contains('guide',"from('mf_classroom_staff')"));add('Mounty media prepare',contains('guide',"action:'prepare_upload'"));add('Mounty media finalize',contains('guide',"action:'finalize_upload'"));add('Mounty media cancel',contains('guide',"action:'cancel_upload'"));add('Mounty draft rollback',contains('guide',".delete().eq('id',broadcastId).eq('status','draft')"));add('Mounty human review',contains('guide','Revísalo antes de enviar'));
for(const x of ['Toda la comunidad','Un ciclo','Un grado','Un estudiante','Estudiantes seleccionados','24 horas'])add(`Mounty UI ${x}`,contains('guide',x));
add('single student maps safely to selected students backend model',()=>assert.ok(has(files.guide,"a.type==='single_student'")&&has(files.guide,"type:'selected_students'")));add('legacy dashboard Mounty Compose routes to unified flow',contains('finalFlow',"['broadcast','mountyCompose']"));
add('teacher observer scoped',notContains('teacher','observer.observe(document.body'));add('teacher render guard',contains('teacher','teacherPanel'));add('teacher classroom staff scope',contains('teacher',"from('mf_classroom_staff')"));add('notification timer cleanup',contains('notifications','clearInterval(timer)'));add('notification listener cleanup',contains('notifications',"removeEventListener('visibilitychange'"));
add('account deletion request uses authenticated endpoint',contains('accountControls','mountain-account-deletion-request'));add('account deletion confirmation exists',contains('accountControls','¿Deseas solicitar la eliminación'));add('public privacy policy explains data categories',contains('privacy','Datos que puede tratar la aplicación'));add('public privacy policy links deletion resource',contains('privacy','account-deletion.html'));add('external deletion page invokes public endpoint',contains('deletion','mountain-account-deletion-public'));add('external deletion page has identity fields',()=>assert.ok(has(files.deletion,'deleteName')&&has(files.deletion,'deleteEmail')));
add('offline network listener',contains('network',"addEventListener('offline'"));add('online network listener',contains('network',"addEventListener('online'"));add('focus-visible accessibility style',contains('a11y',':focus-visible'));add('reduced motion accessibility style',contains('a11y','prefers-reduced-motion'));add('forced colors accessibility style',contains('a11y','forced-colors'));add('attachment signed read',contains('finalFlow',"action:'signed_read'"));add('attachment Safari tab',contains('finalFlow',"window.open('about:blank'"));add('network rejected promises',contains('network','unhandledrejection'));add('PWA standalone',()=>assert.equal(manifest.display,'standalone'));
add('R5.5 service worker cache',contains('sw','mountain-family-shell-r5-5-managed-access-20260912'));add('SW caches runtime',contains('sw',"'./runtime-v2.js'"));add('SW caches account controls',contains('sw',"'./account-controls-v1.js'"));add('SW caches privacy page',contains('sw',"'./privacy.html'"));add('SW caches a11y stylesheet',contains('sw',"'./styles-a11y-v1.css'"));add('SW caches official 512 logo',contains('sw',"'./assets/mountain-logo-512.png'"));add('SW excludes Supabase',contains('sw',"hostname.includes('supabase.co')"));add('SW no legacy auth',notContains('sw','auth-v5.js'));
for(const [name,source] of Object.entries(files))if(!['html','sw','a11y','privacy','deletion'].includes(name))add(`${name} no malformed quote entity`,()=>assert.equal(/&quot(?!;)/.test(source),false));
for(const [name,fn] of contracts)test(name,fn);
