import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,requestPayload,makeHandler,sha256,boundedBody} from '../functions/mcs-gps/core.mjs';
const credential='a'.repeat(64), now=Date.parse('2026-09-06T20:00:00Z');
const payload={device_id:credential,location:{timestamp:new Date(now).toISOString(),coords:{latitude:0,longitude:0,accuracy:5}}};
const request=body=>new Request('https://example.invalid/mcs-gps',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
test('JSON v9 envelope',()=>assert.equal(normalize(payload).fix.accuracy,5));
test('OsmAnd numeric seconds',()=>assert.equal(normalize({id:credential,lat:'0',lon:'0',accuracy:'2',timestamp:now/1000}).fix.captured,now));
test('OsmAnd milliseconds',()=>assert.equal(normalize({id:credential,lat:'0',lon:'0',accuracy:'2',timestamp:now}).fix.captured,now));
test('Missing credential rejected',()=>assert.throws(()=>normalize({location:payload.location}),/unauthorized/));
test('Legacy public short id rejected',()=>assert.throws(()=>normalize({...payload,device_id:'123456'}),/unauthorized/));
test('Phone number rejected',()=>assert.throws(()=>normalize({...payload,device_id:'8290000000'}),/unauthorized/));
test('Array root rejected',()=>assert.throws(()=>normalize([]),/invalid_payload/));
for(const [name,coords] of [['latitude',{latitude:95,longitude:0,accuracy:5}],['longitude',{latitude:0,longitude:200,accuracy:5}],['accuracy',{latitude:0,longitude:0,accuracy:101}],['missing accuracy',{latitude:0,longitude:0}],['null',{latitude:null,longitude:0,accuracy:5}],['empty',{latitude:'',longitude:0,accuracy:5}],['boolean',{latitude:true,longitude:0,accuracy:5}]])test('Reject '+name,()=>assert.equal(normalize({...payload,location:{...payload.location,coords}}).fix,null));
test('Invalid validity flag',()=>assert.equal(normalize({...payload,location:{...payload.location,valid:false}}).fix,null));
test('Missing timezone not guessed',()=>assert.equal(normalize({...payload,location:{...payload.location,timestamp:'2026-09-06 20:00:00'}}).fix,null));
test('Newest of a batch',()=>assert.equal(normalize({...payload,location:[{...payload.location,timestamp:new Date(now-1000).toISOString()},payload.location]}).fix.captured,now));
test('Oversized batch rejected',()=>assert.throws(()=>normalize({...payload,location:Array(51).fill(payload.location)}),/invalid_batch/));
test('JSON request parsed',async()=>assert.deepEqual(await requestPayload(request(payload)),payload));
test('GET OsmAnd parsed',async()=>assert.equal((await requestPayload(new Request('https://example.invalid/?id='+credential+'&lat=0'))).id,credential));
test('Form parsed',async()=>assert.equal((await requestPayload(new Request('https://example.invalid/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:'id='+credential}))).id,credential));
test('Bounded body',async()=>assert.rejects(boundedBody(new Request('https://example.invalid',{method:'POST',body:'x'.repeat(100)}),50),/payload_too_large/));
test('Hash stable without plaintext',async()=>assert.equal((await sha256(credential)).length,64));
test('Unauthenticated handler stops before RPC',async()=>{let called=false;const r=await makeHandler({rpc:async()=>{called=true;}})(request({device_id:'123'}));assert.equal(r.status,401);assert.equal(called,false);});
test('RPC error fails closed',async()=>{const r=await makeHandler({now:()=>now,rpc:async()=>{throw Error('PRIVATE');}})(request(payload));assert.equal(r.status,503);assert.equal((await r.text()).includes('PRIVATE'),false);});
test('Allowlisted success response',async()=>{const r=await makeHandler({now:()=>now,rpc:async args=>{assert.equal(args.p_lat,0);assert.notEqual(args.p_hash,credential);return {code:200,status:'position_received_private_test',accepted:true,latitude:0,secret:credential};}})(request(payload));assert.equal(r.status,200);const body=await r.json();assert.deepEqual(Object.keys(body).sort(),['accepted','status']);assert.match(r.headers.get('cache-control'),/no-store/);});
test('Stale coordinates not passed to DB',async()=>{await makeHandler({now:()=>now+240000,rpc:async args=>{assert.equal(args.p_lat,null);return {code:200,status:'discarded_invalid_fix',accepted:false};}})(request(payload));});
test('Future coordinates not passed to DB',async()=>{await makeHandler({now:()=>now-60000,rpc:async args=>{assert.equal(args.p_lat,null);return {code:200,status:'discarded_invalid_fix',accepted:false};}})(request(payload));});
test('No GPS returned from health',async()=>{const r=await makeHandler({rpc:async()=>{throw Error();}})(new Request('https://example.invalid/mcs-gps'));assert.equal(r.status,200);assert.equal((await r.json()).family_tracking,false);});
test('No global CORS permission',async()=>{const r=await makeHandler({rpc:async()=>{throw Error();}})(new Request('https://example.invalid/mcs-gps'));assert.equal(r.headers.has('access-control-allow-origin'),false);});
test('Oversized POST query rejected',async()=>assert.rejects(requestPayload(new Request('https://example.invalid/?x='+('a'.repeat(8200)),{method:'POST'})),/payload_too_large/));
test('Method rejected',async()=>{const r=await makeHandler({rpc:async()=>{throw Error();}})(new Request('https://example.invalid/',{method:'DELETE'}));assert.equal(r.status,405);});
test('Malformed JSON rejected',async()=>{const r=await makeHandler({rpc:async()=>{throw Error();}})(new Request('https://example.invalid/',{method:'POST',headers:{'content-type':'application/json'},body:'{'}));assert.equal(r.status,400);});
test('Unsupported content rejected',async()=>{const r=await makeHandler({rpc:async()=>{throw Error();}})(new Request('https://example.invalid/',{method:'POST',body:'hello'}));assert.equal(r.status,415);});
